### PR TITLE
MirageOS-ready and µDNS integration

### PR DESCRIPTION
**Pull request by hannesm**
This PR is pretty long, sorry about that.  It does various code cleanups, and frees the library from the `Cohttp_lwt_unix` dependency.  It also adds an example unikernel (using `start'`, not in use atm) that retrieves a let's encrypt certificate by solving the DNS challenge (using µDNS to update the authoritative server).

Another unikernel acts as a secondary DNS server (receives `notify` for zone updates), and requests certificates from let's encrypt (using the DNS challenge as above to update the primary NS) for each certificate signing request received via a zone update (unless there is already a valid (not expired) certificate present, where the public key of the signing request matches the public key of the certificate.  The freshly retrieved certificate is again pushed to the authoritative server, so there's no need for persistent storage here.  Authentication is done via DNS TSIG keys (shared secrets used for HMAC).

While developing the latter, I had to tweak the API so that an initialisation phase is done first (agreeing to terms of service), and later certificates are issued in sequence (using the same `t`).

This is ready for review, and merge, a release of µDNS should predate a let's encrypt release.

### CODE REVIEW

**Comment by hannesm** [comment]
hmm, maybe I opened this too early... I guess there should be some modularisation to avoid a hard dependency on µDNS, I'll try to rework that in the upcoming months..

**Comment by mmaker** [comment]
Hey, sorry it took me so long to review this. I tried to sort out a little bit better your commits and rebase them without unikernels since the beginning. Could you take a quick look at it please? 
Also, I can remove from .merlin
`cohttp-mirage`, `mirage-conduit`, `mirage-types-lwt` at this point right?

**Comment by hannesm** [comment]
oh, thanks. I'll try to take a look what you did (hope to find some time for this this week).

**Comment by hannesm** [comment]
i pushed some more changes here, which should be good to merge. some API changes for udns, migration to the dune build system, ... should be good to merge, but a release to the opam repository will need to wait for udns to be released (I also still plan to make letsencrypt, the core, independent of udns again..)

**Comment by mmaker** [comment]
that's great, thanks!

**Pull request merged**
